### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by canadiannomad** [89Mods/Keppy-s-MIDI-Converter-Multiplatform#1]
I feel so close, but I can't seem to get the program to build...
I think some brief instructions would really be helpful. 
What libraries need to be where?
How to compile, esp without Eclipse?
Thanks!

**Comment by 89Mods** [comment]
If you want to just use the program, download it from the downloads section. If you want to modify and build it, you're going to need eclipse and NativeBass, which i linked in the readme.
